version: "3.3"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: ${NUXT_PUBLIC_APP_NAME}
    restart: unless-stopped
    ports:
      - "${NUXT_PORT:-3000}:${NUXT_PORT:-3000}"
    expose:
      - "${NUXT_PORT:-3000}"
    environment:
      - HOST=0.0.0.0
      - PORT=${NUXT_PORT:-3000}
      - NODE_ENV=${NODE_ENV}
      - NUXT_PUBLIC_API_URL=${NUXT_PUBLIC_API_URL}
      - NUXT_PUBLIC_VERSION=${NUXT_PUBLIC_VERSION}